sudo: false
language: node_js
node_js:
  - "node"

cache: yarn
script:
  - yarn install
  - yarn docs:build

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_ACCESS_TOKEN
  target-branch: master
  local-dir: public
  on:
    branch: blog
